// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinControl uIMozillaFirefoxMenuButton = this.UIRunningapplicationsWindow.UIRunningapplicationsToolBar.UIMozillaFirefoxMenuButton;
            WinMenuItem uIMozillaFirefoxMenuItem = this.UIJumpListWindow.UIItemWindow.UIJumpListClient.UIMozillaFirefoxMenuItem;
            WinComboBox uIItemComboBox = this.UIMozillaFirefoxStartPWindow.UINavigationToolbarToolBar.UIItemComboBox;
            WinEdit uIGotoaWebsiteEdit = this.UIMozillaFirefoxStartPWindow.UIItemComboBox.UIGotoaWebsiteEdit;
            WinEdit uILearnEdit = this.UIMozillaFirefoxStartPWindow.UILearnHyperlink.UILearnEdit;
            WinEdit uILearnmoreEdit = this.UIMozillaFirefoxStartPWindow.UILearnmoreHyperlink.UILearnmoreEdit;
            WinControl uIItemPropertyPage = this.UIMozillaFirefoxStartPWindow.UIFreeCoursesTheASPNETApplication.UIItemPropertyPage;
            WinList uIDesktopList = this.UIProgramManagerWindow.UIFolderViewWindow.UIDesktopList;
            #endregion

            // Right-Click 'Mozilla Firefox' MenuButton
            Mouse.Click(uIMozillaFirefoxMenuButton, MouseButtons.Right, ModifierKeys.None, new Point(25, 14));

            // Click 'Mozilla Firefox' menu item
            Mouse.Click(uIMozillaFirefoxMenuItem, new Point(135, 9));

            // Select 'http://localhost:11259/' in combo box
            uIItemComboBox.EditableItem = this.RecordedMethod1Params.UIItemComboBoxEditableItem;

            // Type '{Enter}' in 'Go to a Website' text box
            Keyboard.SendKeys(uIGotoaWebsiteEdit, this.RecordedMethod1Params.UIGotoaWebsiteEditSendKeys, ModifierKeys.None);

            // Element not available

            // Click 'Learn' text box
            Mouse.Click(uILearnEdit, new Point(15, 14));

            // Click 'Learn more' text box
            Mouse.Click(uILearnmoreEdit, new Point(38, 8));

            // Click PropertyPage
            Mouse.Click(uIItemPropertyPage, new Point(1345, 12));

            // Click 'Desktop' list box
            Mouse.Click(uIDesktopList, new Point(1200, 486));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UIRunningapplicationsWindow UIRunningapplicationsWindow
        {
            get
            {
                if ((this.mUIRunningapplicationsWindow == null))
                {
                    this.mUIRunningapplicationsWindow = new UIRunningapplicationsWindow();
                }
                return this.mUIRunningapplicationsWindow;
            }
        }
        
        public UIJumpListWindow UIJumpListWindow
        {
            get
            {
                if ((this.mUIJumpListWindow == null))
                {
                    this.mUIJumpListWindow = new UIJumpListWindow();
                }
                return this.mUIJumpListWindow;
            }
        }
        
        public UIMozillaFirefoxStartPWindow UIMozillaFirefoxStartPWindow
        {
            get
            {
                if ((this.mUIMozillaFirefoxStartPWindow == null))
                {
                    this.mUIMozillaFirefoxStartPWindow = new UIMozillaFirefoxStartPWindow();
                }
                return this.mUIMozillaFirefoxStartPWindow;
            }
        }
        
        public UIProgramManagerWindow UIProgramManagerWindow
        {
            get
            {
                if ((this.mUIProgramManagerWindow == null))
                {
                    this.mUIProgramManagerWindow = new UIProgramManagerWindow();
                }
                return this.mUIProgramManagerWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UIRunningapplicationsWindow mUIRunningapplicationsWindow;
        
        private UIJumpListWindow mUIJumpListWindow;
        
        private UIMozillaFirefoxStartPWindow mUIMozillaFirefoxStartPWindow;
        
        private UIProgramManagerWindow mUIProgramManagerWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Select 'http://localhost:11259/' in combo box
        /// </summary>
        public string UIItemComboBoxEditableItem = "http://localhost:11259/";
        
        /// <summary>
        /// Type '{Enter}' in 'Go to a Website' text box
        /// </summary>
        public string UIGotoaWebsiteEditSendKeys = "{Enter}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIRunningapplicationsWindow : WinWindow
    {
        
        public UIRunningapplicationsWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Running applications";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MSTaskSwWClass";
            this.WindowTitles.Add("Running applications");
            #endregion
        }
        
        #region Properties
        public UIRunningapplicationsToolBar UIRunningapplicationsToolBar
        {
            get
            {
                if ((this.mUIRunningapplicationsToolBar == null))
                {
                    this.mUIRunningapplicationsToolBar = new UIRunningapplicationsToolBar(this);
                }
                return this.mUIRunningapplicationsToolBar;
            }
        }
        #endregion
        
        #region Fields
        private UIRunningapplicationsToolBar mUIRunningapplicationsToolBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIRunningapplicationsToolBar : WinToolBar
    {
        
        public UIRunningapplicationsToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Running applications";
            this.WindowTitles.Add("Running applications");
            #endregion
        }
        
        #region Properties
        public WinControl UIMozillaFirefoxMenuButton
        {
            get
            {
                if ((this.mUIMozillaFirefoxMenuButton == null))
                {
                    this.mUIMozillaFirefoxMenuButton = new WinControl(this);
                    #region Search Criteria
                    this.mUIMozillaFirefoxMenuButton.SearchProperties[UITestControl.PropertyNames.Name] = "Mozilla Firefox";
                    this.mUIMozillaFirefoxMenuButton.SearchProperties[UITestControl.PropertyNames.ControlType] = "MenuButton";
                    this.mUIMozillaFirefoxMenuButton.WindowTitles.Add("Running applications");
                    #endregion
                }
                return this.mUIMozillaFirefoxMenuButton;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIMozillaFirefoxMenuButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIJumpListWindow : WinWindow
    {
        
        public UIJumpListWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Jump List";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DV2ControlHost";
            this.WindowTitles.Add("Jump List");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "5";
            this.WindowTitles.Add("Jump List");
            #endregion
        }
        
        #region Properties
        public UIJumpListClient UIJumpListClient
        {
            get
            {
                if ((this.mUIJumpListClient == null))
                {
                    this.mUIJumpListClient = new UIJumpListClient(this);
                }
                return this.mUIJumpListClient;
            }
        }
        #endregion
        
        #region Fields
        private UIJumpListClient mUIJumpListClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIJumpListClient : WinClient
    {
        
        public UIJumpListClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Jump List");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIMozillaFirefoxMenuItem
        {
            get
            {
                if ((this.mUIMozillaFirefoxMenuItem == null))
                {
                    this.mUIMozillaFirefoxMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIMozillaFirefoxMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Mozilla Firefox";
                    this.mUIMozillaFirefoxMenuItem.WindowTitles.Add("Jump List");
                    #endregion
                }
                return this.mUIMozillaFirefoxMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIMozillaFirefoxMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMozillaFirefoxStartPWindow : WinWindow
    {
        
        public UIMozillaFirefoxStartPWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Mozilla Firefox Start Page - Mozilla Firefox";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MozillaWindowClass";
            this.WindowTitles.Add("Mozilla Firefox Start Page - Mozilla Firefox");
            this.WindowTitles.Add("Home Page - My ASP.NET Application - Mozilla Firefox");
            this.WindowTitles.Add("ASP.NET | The ASP.NET Site - Mozilla Firefox");
            this.WindowTitles.Add("Learn | The ASP.NET Site - Mozilla Firefox");
            this.WindowTitles.Add("Free Courses | The ASP.NET Site - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public UINavigationToolbarToolBar UINavigationToolbarToolBar
        {
            get
            {
                if ((this.mUINavigationToolbarToolBar == null))
                {
                    this.mUINavigationToolbarToolBar = new UINavigationToolbarToolBar(this);
                }
                return this.mUINavigationToolbarToolBar;
            }
        }
        
        public UIItemComboBox UIItemComboBox
        {
            get
            {
                if ((this.mUIItemComboBox == null))
                {
                    this.mUIItemComboBox = new UIItemComboBox(this);
                }
                return this.mUIItemComboBox;
            }
        }
        
        public UILearnHyperlink UILearnHyperlink
        {
            get
            {
                if ((this.mUILearnHyperlink == null))
                {
                    this.mUILearnHyperlink = new UILearnHyperlink(this);
                }
                return this.mUILearnHyperlink;
            }
        }
        
        public UILearnmoreHyperlink UILearnmoreHyperlink
        {
            get
            {
                if ((this.mUILearnmoreHyperlink == null))
                {
                    this.mUILearnmoreHyperlink = new UILearnmoreHyperlink(this);
                }
                return this.mUILearnmoreHyperlink;
            }
        }
        
        public UIFreeCoursesTheASPNETApplication UIFreeCoursesTheASPNETApplication
        {
            get
            {
                if ((this.mUIFreeCoursesTheASPNETApplication == null))
                {
                    this.mUIFreeCoursesTheASPNETApplication = new UIFreeCoursesTheASPNETApplication(this);
                }
                return this.mUIFreeCoursesTheASPNETApplication;
            }
        }
        #endregion
        
        #region Fields
        private UINavigationToolbarToolBar mUINavigationToolbarToolBar;
        
        private UIItemComboBox mUIItemComboBox;
        
        private UILearnHyperlink mUILearnHyperlink;
        
        private UILearnmoreHyperlink mUILearnmoreHyperlink;
        
        private UIFreeCoursesTheASPNETApplication mUIFreeCoursesTheASPNETApplication;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UINavigationToolbarToolBar : WinToolBar
    {
        
        public UINavigationToolbarToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Navigation Toolbar";
            this.WindowTitles.Add("Mozilla Firefox Start Page - Mozilla Firefox");
            this.WindowTitles.Add("Home Page - My ASP.NET Application - Mozilla Firefox");
            this.WindowTitles.Add("ASP.NET | The ASP.NET Site - Mozilla Firefox");
            this.WindowTitles.Add("Learn | The ASP.NET Site - Mozilla Firefox");
            this.WindowTitles.Add("Free Courses | The ASP.NET Site - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIItemComboBox
        {
            get
            {
                if ((this.mUIItemComboBox == null))
                {
                    this.mUIItemComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIItemComboBox.WindowTitles.Add("Mozilla Firefox Start Page - Mozilla Firefox");
                    this.mUIItemComboBox.WindowTitles.Add("Home Page - My ASP.NET Application - Mozilla Firefox");
                    this.mUIItemComboBox.WindowTitles.Add("ASP.NET | The ASP.NET Site - Mozilla Firefox");
                    this.mUIItemComboBox.WindowTitles.Add("Learn | The ASP.NET Site - Mozilla Firefox");
                    this.mUIItemComboBox.WindowTitles.Add("Free Courses | The ASP.NET Site - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIItemComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemComboBox : WinComboBox
    {
        
        public UIItemComboBox(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Mozilla Firefox Start Page - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIGotoaWebsiteEdit
        {
            get
            {
                if ((this.mUIGotoaWebsiteEdit == null))
                {
                    this.mUIGotoaWebsiteEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIGotoaWebsiteEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Go to a Website";
                    this.mUIGotoaWebsiteEdit.WindowTitles.Add("Mozilla Firefox Start Page - Mozilla Firefox");
                    #endregion
                }
                return this.mUIGotoaWebsiteEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIGotoaWebsiteEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILearnHyperlink : WinHyperlink
    {
        
        public UILearnHyperlink(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "Learn";
            this.WindowTitles.Add("ASP.NET | The ASP.NET Site - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UILearnEdit
        {
            get
            {
                if ((this.mUILearnEdit == null))
                {
                    this.mUILearnEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUILearnEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Learn ";
                    this.mUILearnEdit.WindowTitles.Add("ASP.NET | The ASP.NET Site - Mozilla Firefox");
                    #endregion
                }
                return this.mUILearnEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUILearnEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILearnmoreHyperlink : WinHyperlink
    {
        
        public UILearnmoreHyperlink(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "Learn more›";
            this.WindowTitles.Add("Learn | The ASP.NET Site - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UILearnmoreEdit
        {
            get
            {
                if ((this.mUILearnmoreEdit == null))
                {
                    this.mUILearnmoreEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUILearnmoreEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Learn more";
                    this.mUILearnmoreEdit.WindowTitles.Add("Learn | The ASP.NET Site - Mozilla Firefox");
                    #endregion
                }
                return this.mUILearnmoreEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUILearnmoreEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIFreeCoursesTheASPNETApplication : WinControl
    {
        
        public UIFreeCoursesTheASPNETApplication(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Free Courses | The ASP.NET Site - Mozilla Firefox";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Application";
            this.WindowTitles.Add("Free Courses | The ASP.NET Site - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinControl UIItemPropertyPage
        {
            get
            {
                if ((this.mUIItemPropertyPage == null))
                {
                    this.mUIItemPropertyPage = new WinControl(this);
                    #region Search Criteria
                    this.mUIItemPropertyPage.SearchProperties[UITestControl.PropertyNames.ControlType] = "PropertyPage";
                    this.mUIItemPropertyPage.WindowTitles.Add("Free Courses | The ASP.NET Site - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemPropertyPage;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIItemPropertyPage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIProgramManagerWindow : WinWindow
    {
        
        public UIProgramManagerWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Program Manager";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Progman";
            this.WindowTitles.Add("Program Manager");
            #endregion
        }
        
        #region Properties
        public UIFolderViewWindow UIFolderViewWindow
        {
            get
            {
                if ((this.mUIFolderViewWindow == null))
                {
                    this.mUIFolderViewWindow = new UIFolderViewWindow(this);
                }
                return this.mUIFolderViewWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIFolderViewWindow mUIFolderViewWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIFolderViewWindow : WinWindow
    {
        
        public UIFolderViewWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
            this.WindowTitles.Add("Program Manager");
            #endregion
        }
        
        #region Properties
        public WinList UIDesktopList
        {
            get
            {
                if ((this.mUIDesktopList == null))
                {
                    this.mUIDesktopList = new WinList(this);
                    #region Search Criteria
                    this.mUIDesktopList.SearchProperties[WinList.PropertyNames.Name] = "Desktop";
                    this.mUIDesktopList.WindowTitles.Add("Program Manager");
                    #endregion
                }
                return this.mUIDesktopList;
            }
        }
        #endregion
        
        #region Fields
        private WinList mUIDesktopList;
        #endregion
    }
}
